
04:32:42 PM:DEBUG [logger_base.py:13] Mensaje a nivel debug
04:32:42 PM:INFO [logger_base.py:14] Mensaje a nivel info
04:32:42 PM:WARNING [logger_base.py:15] Mensaje a nivel warning
04:32:42 PM:ERROR [logger_base.py:16] Mensaje a nivel error
04:32:42 PM:CRITICAL [logger_base.py:17] Mensaje a nivel critical
05:08:20 PM:DEBUG [Persona.py:49] 
            id persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
05:13:39 PM:DEBUG [Persona.py:49] 
            id persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
05:13:55 PM:DEBUG [Persona.py:49] 
            id persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
05:13:55 PM:DEBUG [Persona.py:51] 
            id persona: None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: jlezpez@mail.com
        
12:04:39 AM:ERROR [Connection.py:29] Ocurrio un error de tipo: invalid dsn: invalid connection option "username"

12:05:26 AM:ERROR [Connection.py:29] Ocurrio un error de tipo: invalid dsn: invalid connection option "username"

12:07:50 AM:DEBUG [Connection.py:26] Conexion exitosa: <connection object at 0x00000268582C29B0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:09:57 AM:DEBUG [Connection.py:26] Conexion exitosa: <connection object at 0x0000016F81CF29B0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:09:57 AM:ERROR [Connection.py:43] Ocurrio un error de tipo: 'NoneType' object has no attribute 'cursor'
12:13:10 AM:DEBUG [Connection.py:26] Conexion exitosa: <connection object at 0x00000271C5A429B0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:13:10 AM:DEBUG [Connection.py:40] Se abrio correctamente el cursor: <cursor object at 0x00000271C6299620; closed: 0>
12:13:46 AM:DEBUG [Connection.py:26] Conexion exitosa: <connection object at 0x000001F87C8A29B0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:13:46 AM:ERROR [Connection.py:43] Ocurrio un error de tipo: 'NoneType' object has no attribute 'cursor'
12:16:08 AM:DEBUG [Connection.py:26] Conexion exitosa: <connection object at 0x00000264CE2B29B0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:16:08 AM:DEBUG [Connection.py:40] Se abrio correctamente el cursor: <cursor object at 0x00000264CEA99620; closed: 0>
12:16:20 AM:DEBUG [Connection.py:26] Conexion exitosa: <connection object at 0x0000014F844229B0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:16:20 AM:DEBUG [Connection.py:40] Se abrio correctamente el cursor: <cursor object at 0x0000014F84C59620; closed: 0>
